import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className=' flex h-16 bg-yellow-300'>
          <form action="/items" className='m-auto flex max-w-screen-lg flex-1 px-4'>
            <input className='h-8 flex-1 text-gray-600 px-2' type="text" name='search' />
            <button className='bg-gray-200 px-2 py-1 text-slate-700' type='submit'>Search</button>
          </form>
        </header>
        <main className='m-auto max-w-screen-xl p-4'>{children}</main>
      </body>
    </html>
  )
}
